Making a warning out of the dbt clone step if it fails to clone a mod… (#1266)

diff --git a/.github/workflows/dbt_reusable.yml b/.github/workflows/dbt_reusable.yml
--- a/.github/workflows/dbt_reusable.yml
+++ b/.github/workflows/dbt_reusable.yml
@@ -145,7 +145,13 @@ jobs:
 
       - name: Clone other gold models
         run: |
+          set +e
           poetry run dbt clone --select models/gold --exclude state:modified.body+ --state ./ --project-dir ./transform --profiles-dir ./transform/profiles --target ${{ inputs.dbt-target }} --full-refresh
+          status=$?
+          if [ $status -ne 0 ]; then
+            echo "::warning file=clone-gold-models::dbt clone command failed with status $status, continuing..."
+          fi
+          exit 0
         env:
           DATABRICKS_HOST: ${{ env.DATABRICKS_WORKSPACE_URL }}
           DATABRICKS_HTTP_PATH: /sql/1.0/warehouses/${{ env.DATABRICKS_WAREHOUSE_DBT_ID }}
